/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package est.ups.edu.ec.view;

import est.ups.edu.ec.controller.TemperatureController;
import est.ups.edu.ec.model.CelsiusDevice;
import est.ups.edu.ec.model.FahrenheitDevice;
import est.ups.edu.ec.model.FahrenheitToCelsiusAdapter;
import est.ups.edu.ec.model.ITemperatureDevice;
import java.util.List;

/**
 *
 * @author ue0100065z
 */
public class TemperatureView1 extends javax.swing.JFrame {

    TemperatureController controller;
    /**
     * Creates new form TemperatureView1
     */
    public TemperatureView1() {
        controller = new TemperatureController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCelsius = new javax.swing.JButton();
        btnfrain = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Temperaturas");

        btnCelsius.setText("Agregar Dsipositivo en Celcius");
        btnCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelsiusActionPerformed(evt);
            }
        });

        btnfrain.setText("Agregar Dsipositivo en Farinheith");
        btnfrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfrainActionPerformed(evt);
            }
        });

        btnList.setText("Consultar Temperaturas");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnCelsius)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnfrain)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnList)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCelsius)
                    .addComponent(btnfrain)
                    .addComponent(btnList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelsiusActionPerformed
        agregarCelcius();
    }//GEN-LAST:event_btnCelsiusActionPerformed

    private void btnfrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfrainActionPerformed
        agregarFahrenheit();
    }//GEN-LAST:event_btnfrainActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        listTemperatures();
    }//GEN-LAST:event_btnListActionPerformed

    
    private void agregarCelcius(){
        String temp = javax.swing.JOptionPane.showInputDialog("Ingrese temperatura en celsius");
        if(temp.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "No se ha ingresado un valor de temperatura", "Temperatura en Celsius", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        ITemperatureDevice celsiusDevice = new CelsiusDevice(Double.parseDouble(temp));
        controller.addDeviceTemperature(celsiusDevice);
    }
    private void agregarFahrenheit(){
        String temp = javax.swing.JOptionPane.showInputDialog("Ingrese temperatura en celsius");
        if(temp.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, "No se ha ingresado un valor de temperatura", "Temperatura en Celsius", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        FahrenheitDevice fahrenheitDevice = new FahrenheitDevice(Double.parseDouble(temp));
        ITemperatureDevice fahrenheitAdapter = new FahrenheitToCelsiusAdapter(fahrenheitDevice);
        controller.addDeviceTemperature(fahrenheitAdapter);
    }
    
    private void listTemperatures(){
        jTextArea1.setText("");
        List<Double> temperatures = controller.getTemperatures();
        jTextArea1.append("Temperaturas en Celsius:\n");
        for (double temp : temperatures) {
            jTextArea1.append(temp + " °C\n");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureView1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureView1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCelsius;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnfrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
